# 数据结构

### 变量

在程序语言中，变量用来保存输入的值或计算的结果。 变量可以存放各种不同类型的值， 如单个数值、多个数值（称为向量）、单个字符串、多个字符串（称为字符型向量），等等。 单个数值称为标量。

In [12]:
2000+19

[1] 2019

In [1]:
x1<-2001
x2<-19

x1+x2

[1] 2020

用程序设计语言的术语描述， R语言是动态类型的， 其变量的类型不需要预先声明， 运行过程中允许变量类型改变， 实际上变量赋值是一种“绑定”（binding）， 将一个变量的名称（变量名）与实际的一个存储位置联系在一起。 

In [14]:
var_x <- "Hello"
cat("The class of var_x is ",class(var_x),"
")

var_x <- 34.5
cat("  Now the class of var_x is ",class(var_x),"
")

var_x <- 27L
cat("   Next the class of var_x becomes ",class(var_x),"
")

The class of var_x is  character 
  Now the class of var_x is  numeric 
   Next the class of var_x becomes  integer 


要知道工作空间中当前可用的所有变量，我们使用ls()函数；可以使用rm()函数删除变量，比如`rm(list=ls())`会清理内存。

In [4]:
print(ls())
#rm

[1] "x1" "x2"


### 数据类型


当你创建一个变量，你必须在内存中保留一些空间来存储它们。您可能想存储各种数据类型的信息，如字符，宽字符，整数，浮点，双浮点，布尔等。

R语言基本的数据类型归类为

- 数值型：整数，单精度和双精度
- 逻辑型：TRUE, FALSE
- 字符型：夹在双引号或单引号之间的字符串
- 复数型：具有 `a+bi` 的形式
- 原味型：以二进制形式保存的数据
- 特殊变量：Inf 无穷，NaN 不确定，NA 缺失值，NULL 空的对象

In [5]:
v <- 23.5
print(v)

[1] 23.5


In [6]:
v <- TRUE 
print(v)

[1] TRUE


In [7]:
v <- "TRUE"
print(v)

[1] "TRUE"


In [8]:
v <- 2.2+3.5i
print(v)

[1] 2.2+3.5i


In [10]:
v<-sqrt(-2)
print(v)

Warning message in sqrt(-2):
"产生了NaNs"

[1] NaN


In [13]:
# 缺失值用NA表示。统计计算中经常会遇到缺失值，表示记录丢失、因为错误而不能用、节假日没有数据等。
v<-NA
print(v)

[1] NA


与数据类型相关的常用函数有：

- `typeof()`：查询数据的类型
- `is`函数家族：判别对象类型
- `as`函数家族：转换对象类型
- `class`：查看变量的类型

In [15]:
v <- 23.5
print(v)

[1] 23.5


In [25]:
typeof(v)

[1] "double"

In [17]:
is.numeric(v)

[1] TRUE

In [18]:
as.character(v)

[1] "23.5"

在基本的数据类型之上，R语言构建出更复杂的数据结构或者对象，常用的包括向量、矩阵、多维数组、列表、数据框等；从另一个角度来看，在统计分析中我们需要有效地表达出数据（包括定量变量和定性变量），得构建出符合要求的数据结构。

举例：

- 单个随机变量的样本->向量
- 多个随机变量的样本->矩阵
- 定性变量和定量变量的组合->列表、数据框

### 向量

在 R 语言中，向量是最常用的数据结构，是由相同类型的数据元素组成的序列。

向量数据类型是其他数据类型访问方式，值得了解的知识如下：

- [数值型向量及其运算](http://www.math.pku.edu.cn/teachers/lidf/docs/Rbook/html/_Rbook/prog-type-num.html)
- [逻辑型向量及其运算](http://www.math.pku.edu.cn/teachers/lidf/docs/Rbook/html/_Rbook/prog-type-logi.html)
- [字符型数据及其处理](http://www.math.pku.edu.cn/teachers/lidf/docs/Rbook/html/_Rbook/prog-type-char.html)

但由于时间和能力有限，并且避免混乱，主要围绕数值型向量讲解，并穿插另两种类型的向量：

- 构建
- 运算
- 函数
- 下标

向量一般用 `c()` 或者特定函数创建

In [5]:
my_vector<-c(10.4,5.6,3.1,6.4,21.7,44)
my_vector
class(my_vector)

[1] 10.4  5.6  3.1  6.4 21.7 44.0

[1] "numeric"

用 `print()` 函数显示向量或在命令行中显示向量时， 每行显示的行首会有方括号和数字序号， 代表该行显示的第一个向量元素的下标。

In [27]:
print(my_vector)

[1] 10.4  5.6  3.1  6.4 21.7


我们常常调用特定函数来产生有规律的向量。

- 等差数列
- `seq()` 等距间隔数列
- `rep()` 重复函数
- `r+分布` 随机有规律的数据（符合各种分布函数）

In [18]:
my_vector<-1:10
print(my_vector)

 [1]  1  2  3  4  5  6  7  8  9 10


In [6]:
?seq
x <- seq(0, 2*pi, length=25)
print(x)

 [1] 0.0000000 0.2617994 0.5235988 0.7853982 1.0471976 1.3089969 1.5707963
 [8] 1.8325957 2.0943951 2.3561945 2.6179939 2.8797933 3.1415927 3.4033920
[15] 3.6651914 3.9269908 4.1887902 4.4505896 4.7123890 4.9741884 5.2359878
[22] 5.4977871 5.7595865 6.0213859 6.2831853


In [7]:
?rep
x<-rep(1:4, length.out=10)
print(x)

 [1] 1 2 3 4 1 2 3 4 1 2


In [8]:
?rnorm
rnorm(5,0,2)

[1]  1.18815486 -0.01159638 -1.69114046 -1.89437043  0.44664798

向量的运算：

- 标量与标量运算：加减乘除乘方等
- 向量与标量运算：每个元素与标量的运算
- 等长向量运算：对应元素两两运算
- 不等长向量的运算：运算或函数调用的一般规则是每次从头重复利用短的一个

In [33]:
1.5 + 2.3 - (0.6 + 2.1)*1.2 - 1.5/0.5 + 2^3

[1] 5.56

In [34]:
x <- c(1, 10)
x+2

[1]  3 12

In [35]:
x1 <- c(1, 10)
x2 <- c(4, 2)
x1 + x2

[1]  5 12

In [36]:
x1 <- c(10, 20)
x2 <- c(1, 3, 5, 7)
x1 + x2

[1] 11 23 15 27

穿插逻辑型向量：

逻辑值一般产生自比较，向量比较结果为逻辑型向量，比较运算符包括：

```R
<   <=  >  >=  ==  !=  %in%
```

常用于比较的变量有数值型变量和特殊变量

In [10]:
c(1, 3, 5, 2) > c(2, 4)

[1] FALSE FALSE  TRUE FALSE

In [40]:
is.na(c(1, NA, 3) > 2)

[1] FALSE  TRUE FALSE

向量比较遵从R的向量间运算的一般规则： 

向量与标量的运算是向量每个元素与标量都分别运算一次，等长向量的运算时对应元素的运算，不等长但长度为倍数关系的向量运算是把短的从头重复利用。


In [42]:
c(1, 3, 5) > c(2, 4)

Warning message in c(1, 3, 5) > c(2, 4):
"长的对象长度不是短的对象长度的整倍数"

[1] FALSE FALSE  TRUE

向量函数：

先看看数值型向量的函数

- 向量化的函数：R中的函数一般都是向量化的，如果普通的一元函数以向量为自变量，一般会对每个元素计算。例如：`sqrt`, `log10`, `log`, `exp`, `sin`, `cos`, `tan`。

- 排序函数：`sort()`返回排序结果，`rev()`返回把各元素排列次序反转后的结果，`order()`返回排序用的下标。

- 统计函数： 把输入向量看作样本，计算样本统计量。`sum`求和, `mean`求平均值, `var`求样本方差, `sd`求样本标准差, `min`求最小值, `max`求最大值, `range`求最小值和最大值


In [43]:
sqrt(c(1, 4, 6.25))

[1] 1.0 2.0 2.5

In [44]:
x <- c(33, 55, 11)
# 排序
sort(x)

# 倒排序
rev(sort(x))

# 排序后的下标
order(x)

# 用排序后的下标来排序
x[order(x)]

[1] 11 33 55

[1] 55 33 11

[1] 3 1 2

[1] 11 33 55

In [53]:
v<-rnorm(5,0,2)

# 求和
sum(v)

# 求平均值
mean(v)

# 求样本方差
var(v)

# 求样本标准差
sd(v)

[1] -0.965396

[1] -0.1930792

[1] 3.773911

[1] 1.942656

看看与逻辑型向量有关的函数，主要与比较有关：

- 若`cond`是逻辑向量， 用`all(cond)`测试`cond`的所有元素为真；用`any(cond)`测试`cond`至少一个元素为真；`cond`中允许有缺失值，结果可能为缺失值。
- `which` 返回真值对应的所有下标
- `identical(x,y)` 比较两个对象x和y的内容是否完全相同
- `duplicated()` 返回每个元素是否为重复值的结果


In [55]:
c(1, NA, 3) > 2

all(c(1, NA, 3) > 2)

any(c(1, NA, 3) > 2)

all(NA)

any(NA)

[1] FALSE    NA  TRUE

[1] FALSE

[1] TRUE

[1] NA

[1] NA

In [56]:
identical(c(1,2,3), c(1,2,NA))

identical(c(1L,2L,3L), c(1,2,3))

[1] FALSE

[1] FALSE

In [57]:
duplicated(c(1,2,1,3,NA,4,NA))

[1] FALSE FALSE  TRUE FALSE FALSE FALSE  TRUE

看看与字符型向量相关的函数：

- `paste()`函数，用来连接两个字符型向量，默认用空格连接
- `substr(x, start, stop)`函数，从字符串x中去除从第start个到第stop个的子串
- `strsplit()`函数，把一个字符串按照某种分隔符拆分开
- `gsub()`函数，替换字符串中的子串，支持正则表达式

In [59]:
#？paste
paste("x", 1:3, sep="")

[1] "x1" "x2" "x3"

In [61]:
#?substr
substr(c('JAN07', 'MAR66'), 1, 3)

[1] "JAN" "MAR"

In [62]:
#?strsplit
x <- '10,8,7'
strsplit(x, ',', fixed=TRUE)[[1]]

[1] "10" "8"  "7"

In [63]:
x <- '1, 3; 5'
gsub(';', ',', x, fixed=TRUE)

[1] "1, 3, 5"

### 向量的下标与子集

对向量x, 在后面加方括号和下标可以访问向量的元素和子集，有关下标的知识比较多且比较重要：

- 正整数下标
- 负整数下标
- 空下标
- 下标超界
- 逻辑下标
- `which`函数
- 元素名
- 下标映射
- 集合运算


In [69]:
# 取出第二个元素
x <- c(1, 4, 6.25)
x[2]

# 修改第二个元素
x[2] <- 99; x

# 取出第1、3号元素
x[c(1,3)]

# 修改第1、3号元素
x[c(1,3)] <- c(11, 13);x

[1] 4

[1]  1.00 99.00  6.25

[1] 1.00 6.25

[1] 11 99 13

负下标表示扣除相应的元素后的子集

In [71]:
x <- c(1,4,6.25)
x[-2]
x[-c(1,3)]

[1] 1.00 6.25

[1] 4

`x[]`表示取x的全部元素作为子集，这与x本身不同

In [123]:
x <- c(1,4,6.25)
x[] <- 999
x

[1] 999 999 999

设向量x长度为，则使用正整数下标时下标应在{1,2,...,n}中取值。如果使用大于n的下标，读取时返回缺失值，并不出错。给超出n的下标元素赋值，则向量自动变长， 中间没有赋值的元素为缺失值。 

In [72]:
x <- c(1,4,6.25)
x[5]

[1] NA

In [73]:
x[5] <- 9
x

[1] 1.00 4.00 6.25   NA 9.00

下标可以是与向量等长的逻辑表达式，一般是关于本向量或者与本向量等长的其它向量的比较结果，主要用于对向量或者数据框取子集；要注意的是，如果逻辑下标中有缺失值，对应结果也是缺失值。所以，在用逻辑下标作子集选择时，一定要考虑到缺失值问题，正确的做法是加上`!is.na`前提。


In [75]:
x <- c(1,4,6.25)
x[x > 3]

x <- c(1, 4, 6.25, NA)
x[x > 2]
x[!is.na(x) & x > 2]


[1] 4.00 6.25

[1] 4.00 6.25   NA

[1] 4.00 6.25

`which()`函数常常用于提供满足条件的逻辑下表

In [76]:
x <- c(3, 4, 3, 5, 7, 5, 9)
which(x > 5)

which.min(x)

which.max(x)

[1] 5 7

[1] 1

[1] 7

向量可以为每个元素命名，并且用元素名或元素名向量作为向量的下标

In [79]:
ages <- c("李明"=30, "张聪"=25, "刘颖"=28)
ages["张聪"]
ages[c("李明", "刘颖")]

张聪 
  25

李明 刘颖 
  30   28

为向量的元素命名，实际上建立了字符串到数值的映射表，而R向量支持多种下标映射表，比如整数向量和字符型向量

In [81]:
price.map <- c(68, 88, 168)
items <- c(3,2,1,1,2,2,3)
y <- price.map[items]; print(y)

[1] 168  88  68  68  88  88 168


In [83]:
sex.color <- c('男'='blue', '女'='red')
sex <- c("男", "男", "女", "女", "男", "女", "女", "女", "女", "男")
cols <- sex.color[sex]; print(cols)
unname(cols)

    男     男     女     女     男     女     女     女     女     男 
"blue" "blue"  "red"  "red" "blue"  "red"  "red"  "red"  "red" "blue" 


[1] "blue" "blue" "red"  "red"  "blue" "red"  "red"  "red"  "red"  "blue"

练习：

把上述文件class.csv读入为R数据框d.class, 并取出其中的name和age列到变量name和age中，代码如下
```
d.class <- read.csv('class.csv', header=TRUE, stringsAsFactors=FALSE)
name <- d.class[,'name']
age <- d.class[,'age']
```
需要完成：

1. 求出age中第3, 5, 7号的值；
2. 用变量age, 求出达到15岁及以上的那些值；
3. 用变量name和age, 求出Mary与James的年龄;
4. 求age中除Mary与James这两人之外的那些人的年龄值，保存到变量age1中;



In [90]:
d.class <- read.csv('./materials/class.csv', header=TRUE, stringsAsFactors=FALSE)
name <- d.class[,'name']
age <- d.class[,'age']
str(d.class)
head(d.class)

'data.frame':	19 obs. of  5 variables:
 $ name  : chr  "Alice" "Becka" "Gail" "Karen" ...
 $ sex   : chr  "F" "F" "F" "F" ...
 $ age   : int  13 13 14 12 12 15 11 15 14 14 ...
 $ height: num  56.5 65.3 64.3 56.3 59.8 66.5 51.3 62.5 62.8 69 ...
 $ weight: num  84 98 90 77 84.5 ...


name  sex age height weight
1 Alice F   13  56.5    84.0 
2 Becka F   13  65.3    98.0 
3 Gail  F   14  64.3    90.0 
4 Karen F   12  56.3    77.0 
5 Kathy F   12  59.8    84.5 
6 Mary  F   15  66.5   112.0

In [88]:
age[c(3,5,7)]

[1] 14 12 11

In [98]:
d.class[which(age>15),]

name   sex age height weight
16 Philip M   16  72     150

In [100]:
age[which(name=='Mary')]
age[which(name=='James')]

[1] 15

[1] 12

In [103]:
age1<-age[name!='Mary' || name!='James']
age1

[1] 13 13 14 12 12 15 11 15 14 14 14 15 12 13 12 16 12 11 15

### 矩阵

在 R 语言中，矩阵是一种特殊类型的向量。矩阵是数据元素以二维矩形排布的集合，矩阵有行和列。

一般使用 `matrix()` 函数创建，矩阵元素可以通过列和行的索引来引用，了解简单的矩阵操作：
- 维度
- 子集
- 合并

In [11]:
?matrix
mdat<-matrix(c(1,2,3,11,12,13),nrow=2,ncol=3)
print(mdat)

print(mdat[2,2])

     [,1] [,2] [,3]
[1,]    1    3   12
[2,]    2   11   13
[1] 11


In [120]:
# 维度

nrow(mdat)

ncol(mdat)

dim(mdat)

[1] 2

[1] 3

[1] 2 3

In [125]:
# 子集

mdat[1,]

mdat[,1]

mdat[1:2, c(1,3)]

[1]  1  3 12

[1] 1 2

[,1] [,2]
[1,] 1    12  
[2,] 2    13

In [127]:
# 合并

cbind(mdat, c(1,-1))

rbind(mdat, c(-1,-1,10))

[,1] [,2] [,3] [,4]
[1,] 1     3   12    1  
[2,] 2    11   13   -1

[,1] [,2] [,3]
[1,]  1    3   12  
[2,]  2   11   13  
[3,] -1   -1   10

常常用到R运算符对矩阵执行各种数学运算：

- 简单的运算：转置、逐元素相乘除、矩阵相乘除
- 数值计算：求逆、谱分解、奇异值分解、QR分解


In [4]:
# Create two 2x3 matrices.
matrix1 <- matrix(c(3, 9, -1, 4, 2, 6), nrow = 2)
print(matrix1)

matrix2 <- matrix(c(5, 2, 0, 9, 3, 4), nrow = 2)
print(matrix2)

# Multiply the Hadamard matrices.
result <- matrix1 * matrix2
cat("Result of Hadamard multiplication","
")
print(result)

     [,1] [,2] [,3]
[1,]    3   -1    2
[2,]    9    4    6
     [,1] [,2] [,3]
[1,]    5    0    3
[2,]    2    9    4
Result of Hadamard multiplication 
     [,1] [,2] [,3]
[1,]   15    0    6
[2,]   18   36   24


In [5]:
# Divide the matrices
result <- matrix1 / matrix2
cat("Result of division","
")
print(result)

# Multiply the matrices.
result <- t(matrix1) %*% matrix2
cat("Result of multiplication","
")
print(result)

Result of division 
     [,1]      [,2]      [,3]
[1,]  0.6      -Inf 0.6666667
[2,]  4.5 0.4444444 1.5000000
Result of multiplication 
     [,1] [,2] [,3]
[1,]   33   81   45
[2,]    3   36   13
[3,]   22   54   30


对于向量，可以用 `sum` ，`mean`等函数对其进行计算。对于矩阵或数组也可以作这类函数的jisaun，但其结果相当于对矩阵或数组全部数据做运算，当计算矩阵各行的和时会很不方便，R语言提供`apply()`函数来完成这项工作。其使用格式为：

```
apply(X, MARGIN, FUN, ...)
```

参数X为数组或矩阵，MARGIN为指定数组或矩阵的维，FUN为用来计算的函数。

In [1]:
A<-matrix(1:6, nrow=2);A

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [2]:
sum(A)

[1] 21

In [3]:
apply(A, 1, sum)

[1]  9 12

### 因子

统计中的变量有几种重要类别：区间变量、名义变量和有序变量。区间变量取连续的数值，可以进行求和、平均值等运算。名义变量和有序变量取离散值，可以用数值代表，也可以是字符型值，其具体数值没有加减乘除的意义，不能用来计算，而只能用来分类或计数。

在R中，使用因子(factor)来表示名义变量或有序变量。分类变量, 如性别、省份、职业等；有序变量，如打分结果、疾病严重程度等。

一般使用 `factor()` 函数通过将向量作为输入创建因子，其使用格式为：
```
factor(x = character(), levels, labels = levels,
       exclude = NA, ordered = is.ordered(x), nmax = NA)
```

- x为数据向量，也是被转换成因子的向量
- levels为可选向量，表示因子水平，当此参数去默认值时，由x元素中的不同值来确定
- labels为可选向量，用来指定各水平的名称，取默认值时，取levels的值

In [131]:
#?factor

# Create a vector as input.
data <- c("East","West","East","North","North","East","West","West","West","East","North")

print(data)
print(is.factor(data))

# Apply the factor function.
factor_data <- factor(data)

print(factor_data)
print(is.factor(factor_data))

# Apply the factor function with required order of the level.
new_order_data <- factor(factor_data,levels = c("East","West","North"))
print(new_order_data)

 [1] "East"  "West"  "East"  "North" "North" "East"  "West"  "West"  "West" 
[10] "East"  "North"
[1] FALSE
 [1] East  West  East  North North East  West  West  West  East  North
Levels: East North West
[1] TRUE
 [1] East  West  East  North North East  West  West  West  East  North
Levels: East West North


与因子类型有关的函数：
- `table()`函数，统计因子各水平的出现次数
- `tapply()`函数，按照因子分组然后每组计算另一变量的概括统计
- forcats包的因子函数，在分类变量类数较多时，往往需要对因子水平另外排序、合并等， forcats包提供了一些针对因子的方便函数。

In [140]:
x <- c("男", "女", "男", "男",  "女")
sex <- factor(x)

# ?table
table(sex)

sex
男 女 
 3  2 

In [141]:
# ?tapply

h <- c(165, 170, 168, 172, 159)
tapply(h, sex, FUN=mean, simplify=TRUE)

男       女 
168.3333 164.5000

### 数据帧

数据框是表或二维阵列状结构，每列为一个变量，每行为一个观测样本，有点像Excel表格的样子。

以下是数据框的特性：

- 列名称应为非空，行名称应该是唯一的
- 存储在数据帧中的数据（各列）允许有不同类型：数值型向量、因子、字符型向量、日期时间向量
- 每个列应包含相同数量的数据项

数据框可以用`data.frame()`函数生成，可以看成是矩阵的推广，也可以看作一种特殊的列表。

In [2]:
# Create the data frame.
emp.data <- data.frame(
   emp_id = c (1:5), 
   emp_name = c("Rick","Dan","Michelle","Ryan","Gary"),
   salary = c(623.3,515.2,611.0,729.0,843.25), 
   age = c(30,32,34,37,40),
   start_date = as.Date(c("2012-01-01", "2013-09-23", "2014-11-15", "2014-05-11",
      "2015-03-27")),
   stringsAsFactors = FALSE # 避免字符型转换成因子
)
# Print the data frame.
print(emp.data) 

  emp_id emp_name salary age start_date
1      1     Rick 623.30  30 2012-01-01
2      2      Dan 515.20  32 2013-09-23
3      3 Michelle 611.00  34 2014-11-15
4      4     Ryan 729.00  37 2014-05-11
5      5     Gary 843.25  40 2015-03-27


数据框内容访问:
- 矩阵格式
- 列名
- 双括号
- `attach()`

In [3]:
emp.data[1,2]

emp.data[1,]

emp.data['salary'] # 单括号取子集

emp.data[['salary']] # 双括号取元素

emp.data$emp_id

attach(emp.data)

age

[1] "Rick"

emp_id emp_name salary age start_date
1 1      Rick     623.3  30  2012-01-01

salary
1 623.30
2 515.20
3 611.00
4 729.00
5 843.25

[1] 623.30 515.20 611.00 729.00 843.25

[1] 1 2 3 4 5

[1] 30 32 34 37 40

如果需要作矩阵（或数组）各行或各列的某种运算，需要用到 `apply()` 函数。对于列表和数据框，需要作某种变量的计算就需要用到 `lapply()` 函数或 `sapply()` 函数。两个函数的使用方法相同，其差别在于：`lapply()` 的返回值为列表， `sapply()` 的返回值为数据框。

In [7]:
lapply(emp.data[c("age", "salary")], mean)

$age
[1] 34.6

$salary
[1] 664.35

In [8]:
sapply(emp.data[c("age", "salary")], mean)

age salary 
 34.60 664.35

### 列表

列表是一种特别的对象集合，各元素的类型可以是任意对象，不同元素不必是同一类型。

一般使用 `list()` 函数创建，列表元素的引用方式有：

- 列表名[[下标]]
- 列表名[[元素名]]
- 列表名\$元素名

列表的一个元素也可以称为列表的一个“变量”，单个列表元素必须用两重方括号格式访问，如果使用单重方括号对列表取子集，结果还是列表而不是列表元素。

此外，列表一般都应该有元素名，元素名可以看成是变量名，列表中的每个元素看成一个变量。

In [144]:
my_list <- list("Red", TRUE, 51.23, name='long')
print(my_list)

print(my_list[[1]])
print(my_list[["name"]])
print(my_list$name)

[[1]]
[1] "Red"

[[2]]
[1] TRUE

[[3]]
[1] 51.23

$name
[1] "long"

[1] "Red"
[1] "long"
[1] "long"


列表的主要目的是提供R分析结果输出包装：输出一个变量，这个变量包括回归系数、预测值、残差、检验结果等等一系列不能放到规则形状数据结构中的内容。 

列表与数据框：数据框也是列表的一种，但是数据框要求各列等长，而列表不要求。

列表与向量：列表的不同元素的类型可以不同

In [147]:
# 返回列表的函数示例 - strsplit()

x <- c('10, 8, 7', '5, 2, 2', '3, 7, 8', '8, 8, 9')
res <- strsplit(x, ',');
print(res)

[[1]]
[1] "10" " 8" " 7"

[[2]]
[1] "5"  " 2" " 2"

[[3]]
[1] "3"  " 7" " 8"

[[4]]
[1] "8"  " 8" " 9"

